server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: app_json_logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: nodejs-app
          environment: development
          __path__: /var/log/app/*.log
    
    pipeline_stages:
      # Парсим JSON логи
      - json:
          expressions:
            level: level
            message: message
            timestamp: timestamp
            requestId: requestId
            method: method
            url: url
            statusCode: statusCode
            duration: duration
    
      # Добавляем лейблы из полей JSON
      - labels:
          level:
          method:
          statusCode:
    
      # Преобразуем timestamp в правильный формат
      - timestamp:
          source: timestamp
          format: RFC3339
    
      # Добавляем статические лейблы
      - static_labels:
          app: monitoring-demo
          component: backend

  - job_name: app_container_logs
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 10s
    
    relabel_configs:
      # Только логи нашего приложения
      - source_labels: ['__meta_docker_container_name']
        regex: '/(.*)'
        target_label: 'container'
      - source_labels: ['__meta_docker_container_name']
        regex: 'monitoring-demo-app'
        action: keep
    
    pipeline_stages:
      - regex:
          expression: '^(?P<timestamp>\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}) (?P<level>\w+) (?P<message>.*)'
      - labels:
          level: